name: Build & push to Docker Hub

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'build'
  cancel-in-progress: true

env:
  BUILD_PATH: '.'

jobs:
  build:
    name: Build the image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get Git SHA
        id: git_sha
        run: |
          echo "full=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
          build-args: |
            GIT_COMMIT=${{ steps.git_sha.outputs.full }}
            GIT_COMMIT_SHORT=${{ steps.git_sha.outputs.short }}

  post:
    name: Post the update request
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: KessokuTeaTime/action-kessoku-private-ci@main
        with:
          auth: ${{ secrets.KTT_API_TOKEN }}
          endpoint: ${{ vars.KTT_API_ENDPOINT }}
          payload: |
            {
              "image": "${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest",
              "target": "www"
            }
